# Site settings
url: http://ryngonzalez.com
title: "Kathryn Gonzalez | Designer and Engineer"
description: "Kathryn Gonzalez, Designer Technologist. Working with React, Javascript, Swift, Kotlin. Web/iOS/Android Engineer. Erstwhile Product Designer."
# Contact info
name: Kathryn Gonzalez
email: kathrynmichellegonzalez@gmail.com
twitter_username: ryngonzalez
github_username:  ryngonzalez
dribbble_username: ryngonzalez

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Jekyll configuration
sass:
  sass_dir: styles/_sass
destination: ./build
highlighter: pygments

# Collections
collections:
  work:
    output: true
    directory: ./work
    permalink: /work/:path/
