# Site settings
url: http://ryngonzalez.com
title: "Ryan Gonzalez | Designer and Engineer"
description: "Ryan Gonzalez, Designer and Engineer. Working with Ruby, Javascript, C++, Angular. Illsutrations, UI design."
# Contact info
name: Ryan Gonzalez
email: ryan@ionizedmedia.com
twitter_username: ryngonzalez
github_username:  ryngonzalez
dribbble_username: ryngonzalez

# Build settings
markdown: kramdown

# Jekyll configuration
sass:
  sass_dir: styles/_sass
destination: ./build
highlighter: pygments

# Collections
collections:
  work:
    output: true
    directory: ./work
    permalink: /work/:path/

gems:
  - octopress-autoprefixer
